import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_PATH = REPO_ROOT / "scripts"
if str(SCRIPTS_PATH) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_PATH))

import ingest_cn_nl_llm_text as llm_ingest  # noqa: E402


def build_fake_source_payload() -> dict:
    return {
        "document": {
            "document_id": "cn-nl-article11-12-llm",
            "title": "China-Netherlands Tax Treaty Articles 11-12",
            "document_type": "treaty_text",
            "jurisdictions": ["CN", "NL"],
            "notes": ["Generated by constrained LLM document extraction."],
        },
        "parsed_articles": [
            {
                "article_number": "11",
                "article_title": "Interest",
                "article_label": "Article 11",
                "income_type": "interest",
                "summary": "Treaty treatment for interest between the two jurisdictions.",
                "article_notes": ["Beneficial ownership may matter."],
                "paragraphs": [
                    {
                        "paragraph_id": "art11-p2",
                        "paragraph_label": "Article 11(2)",
                        "source_reference": "Article 11(2)",
                        "source_language": "en",
                        "source_segments": [
                            {
                                "segment_id": "art11-p2-s1",
                                "segment_order": 1,
                                "page_hint": None,
                                "source_kind": "article_paragraph",
                                "text_quality": "clean",
                                "normalization_status": "verbatim",
                                "text": "However, such interest may also be taxed in the first-mentioned State, but the tax shall not exceed 10 per cent of the gross amount of the interest.",
                            }
                        ],
                        "extracted_rules": [
                            {
                                "rule_id": "cn-nl-art11-p2-r1",
                                "rule_type": "withholding_tax_cap",
                                "rate": "10%",
                                "direction": "bidirectional",
                                "candidate_rank": 1,
                                "is_primary_candidate": True,
                                "extraction_confidence": 0.91,
                                "derived_from_segments": ["art11-p2-s1"],
                                "conditions": [
                                    "Treaty applicability depends on the facts of the payment."
                                ],
                                "human_review_required": True,
                                "review_reason": "Final eligibility depends on facts outside the current review scope.",
                            }
                        ],
                    }
                ],
            }
        ],
    }


def test_run_ingest_writes_parsed_dataset_and_success_report(tmp_path, monkeypatch):
    input_path = tmp_path / "article11-12.clean.txt"
    parsed_output_path = tmp_path / "llm.parsed.json"
    dataset_output_path = tmp_path / "llm.dataset.json"
    report_output_path = tmp_path / "llm.report.json"
    input_path.write_text("Article 11 Interest\n2. ...", encoding="utf-8")

    monkeypatch.setattr(
        llm_ingest,
        "extract_source_payload_from_text",
        lambda *args, **kwargs: build_fake_source_payload(),
    )
    monkeypatch.setattr(
        llm_ingest,
        "load_config_from_env",
        lambda: type("Config", (), {"model": "deepseek-chat"})(),
    )

    exit_code, report = llm_ingest.run_ingest(
        input_path=input_path,
        parsed_output_path=parsed_output_path,
        dataset_output_path=dataset_output_path,
        report_output_path=report_output_path,
        document_id="cn-nl-article11-12-llm",
        title="China-Netherlands Tax Treaty Articles 11-12",
        document_type="treaty_text",
        jurisdictions=["CN", "NL"],
        source_language="en",
    )

    assert exit_code == 0
    assert parsed_output_path.exists()
    assert dataset_output_path.exists()
    assert report_output_path.exists()
    assert report == {
        "status": "ok",
        "document_id": "cn-nl-article11-12-llm",
        "article_count": 1,
        "paragraph_count": 1,
        "rule_count": 1,
        "llm_provider": "deepseek",
        "llm_model": "deepseek-chat",
    }
    parsed_payload = json.loads(parsed_output_path.read_text(encoding="utf-8"))
    dataset_payload = json.loads(dataset_output_path.read_text(encoding="utf-8"))
    assert parsed_payload["parsed_articles"][0]["article_number"] == "11"
    assert dataset_payload["articles"][0]["paragraphs"][0]["rules"][0]["rate"] == "10%"


def test_run_ingest_writes_error_report_when_llm_extraction_fails(tmp_path, monkeypatch):
    input_path = tmp_path / "article11-12.clean.txt"
    parsed_output_path = tmp_path / "llm.parsed.json"
    dataset_output_path = tmp_path / "llm.dataset.json"
    report_output_path = tmp_path / "llm.report.json"
    input_path.write_text("Article 11 Interest\n2. ...", encoding="utf-8")

    monkeypatch.setattr(
        llm_ingest,
        "extract_source_payload_from_text",
        lambda *args, **kwargs: (_ for _ in ()).throw(
            llm_ingest.LLMDocumentExtractionError("rate extraction timed out")
        ),
    )

    exit_code, report = llm_ingest.run_ingest(
        input_path=input_path,
        parsed_output_path=parsed_output_path,
        dataset_output_path=dataset_output_path,
        report_output_path=report_output_path,
        document_id="cn-nl-article11-12-llm",
        title="China-Netherlands Tax Treaty Articles 11-12",
        document_type="treaty_text",
        jurisdictions=["CN", "NL"],
        source_language="en",
    )

    assert exit_code == 1
    assert not parsed_output_path.exists()
    assert not dataset_output_path.exists()
    assert report_output_path.exists()
    assert report == {
        "status": "error",
        "document_id": "cn-nl-article11-12-llm",
        "error_stage": "llm_extraction",
        "error_message": "rate extraction timed out",
    }
