from __future__ import annotations

import json
import re
from typing import Any
from urllib import error, request

from app.llm_input_parser import (
    LLMInputParserConfig,
    extract_json_content,
    load_config_from_env,
)


class LLMDocumentExtractionError(RuntimeError):
    pass


PERCENT_RATE_PATTERN = re.compile(r"(\d+)\s+per\s+cent", re.IGNORECASE)


def build_request_payload(raw_text: str, model: str, source_language: str) -> dict[str, Any]:
    system_prompt = (
        "You extract structured treaty article data for an offline tax-treaty ingestion pipeline. "
        "Return only JSON with a top-level key parsed_articles. "
        "Each article must include: article_number, article_title, income_type, summary, article_notes, paragraphs. "
        "Each paragraph must include: paragraph_number, source_reference, text, rules. "
        "Each rule must include: rule_type, rate, direction, conditions, review_reason, extraction_confidence. "
        'Required JSON field names include "income_type", "paragraph_number", and "extraction_confidence". '
        "Use income_type only from: dividends, interest, royalties, unknown. "
        "Use direction only from: bidirectional, payer_to_payee, payee_to_payer, unknown. "
        "Keep extraction_confidence between 0 and 1. "
        f"The source language is {source_language}. "
        "If the text does not contain a usable treaty article, return parsed_articles as an empty list."
    )

    return {
        "model": model,
        "temperature": 0,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": raw_text},
        ],
    }


def extract_source_payload_from_text(
    raw_text: str,
    *,
    document_id: str,
    title: str,
    document_type: str,
    jurisdictions: list[str],
    source_language: str = "en",
    config: LLMInputParserConfig | None = None,
) -> dict | None:
    resolved_config = config or load_config_from_env()
    if resolved_config is None:
        return None

    payload = build_request_payload(raw_text, resolved_config.model, source_language)
    body = json.dumps(payload).encode("utf-8")
    http_request = request.Request(
        url=f"{resolved_config.base_url}/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {resolved_config.api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with request.urlopen(http_request, timeout=resolved_config.timeout_seconds) as response:
            response_payload = json.loads(response.read().decode("utf-8"))
    except (error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        raise LLMDocumentExtractionError(str(exc)) from exc

    try:
        content = response_payload["choices"][0]["message"]["content"]
        model_payload = json.loads(extract_json_content(content))
    except (KeyError, IndexError, TypeError, json.JSONDecodeError) as exc:
        raise LLMDocumentExtractionError(
            "Failed to parse structured JSON from LLM document response."
        ) from exc

    return {
        "document": {
            "document_id": document_id,
            "title": title,
            "document_type": document_type,
            "jurisdictions": jurisdictions,
            "notes": [
                "Generated by constrained LLM document extraction."
            ],
        },
        "parsed_articles": [
            normalize_article(article, source_language=source_language)
            for article in model_payload.get("parsed_articles", [])
        ],
    }


def normalize_article(article: dict[str, Any], *, source_language: str) -> dict[str, Any]:
    article_number = str(article["article_number"]).strip()
    article_title = str(article["article_title"]).strip()
    paragraphs = article.get("paragraphs", [])

    return {
        "article_number": article_number,
        "article_title": article_title,
        "article_label": f"Article {article_number}",
        "income_type": normalize_income_type(article.get("income_type")),
        "summary": normalize_optional_text(article.get("summary")),
        "article_notes": normalize_string_list(article.get("article_notes")),
        "paragraphs": [
            normalize_paragraph(
                paragraph,
                article_number=article_number,
                source_language=source_language,
            )
            for paragraph in paragraphs
        ],
    }


def normalize_paragraph(
    paragraph: dict[str, Any],
    *,
    article_number: str,
    source_language: str,
) -> dict[str, Any]:
    paragraph_number = str(paragraph["paragraph_number"]).strip()
    paragraph_id = f"art{article_number}-p{paragraph_number}"
    segment_id = f"{paragraph_id}-s1"
    source_reference = normalize_optional_text(paragraph.get("source_reference"))
    if not source_reference:
        source_reference = f"Article {article_number}({paragraph_number})"
    paragraph_text = normalize_optional_text(paragraph.get("text"))

    rules = paragraph.get("rules", [])
    inferred_rate = infer_rate_from_text(paragraph_text)
    normalized_rules: list[dict[str, Any]] = []
    primary_assigned = False
    for index, rule in enumerate(rules, start=1):
        is_primary = False
        if not primary_assigned:
            is_primary = True
            primary_assigned = True
        rule_type = normalize_optional_text(rule.get("rule_type")) or "treaty_scope_note"
        normalized_rate = normalize_rate(rule.get("rate"), inferred_rate)
        normalized_rules.append(
            {
                "rule_id": f"cn-nl-art{article_number}-p{paragraph_number}-r{index}",
                "rule_type": rule_type,
                "rate": normalized_rate,
                "direction": normalize_direction(rule.get("direction")),
                "candidate_rank": index,
                "is_primary_candidate": is_primary,
                "extraction_confidence": normalize_confidence(rule.get("extraction_confidence")),
                "derived_from_segments": [segment_id],
                "conditions": normalize_conditions(
                    normalize_string_list(rule.get("conditions")),
                    rule_type=rule_type,
                    paragraph_text=paragraph_text,
                ),
                "human_review_required": True,
                "review_reason": normalize_review_reason(
                    normalize_optional_text(rule.get("review_reason")),
                    rule_type=rule_type,
                    paragraph_text=paragraph_text,
                    rate=normalized_rate,
                ),
            }
        )

    return {
        "paragraph_id": paragraph_id,
        "paragraph_label": f"Article {article_number}({paragraph_number})",
        "source_reference": source_reference,
        "source_language": normalize_optional_text(paragraph.get("source_language")) or source_language,
        "source_segments": [
            {
                "segment_id": segment_id,
                "segment_order": 1,
                "page_hint": None,
                "source_kind": "article_paragraph",
                "text_quality": "clean",
                "normalization_status": "verbatim",
                "text": paragraph_text,
            }
        ],
        "extracted_rules": normalized_rules,
    }


def normalize_income_type(raw_value: Any) -> str:
    if not isinstance(raw_value, str):
        return "unknown"
    normalized = raw_value.strip().lower()
    if normalized in {"dividends", "interest", "royalties"}:
        return normalized
    return "unknown"


def normalize_direction(raw_value: Any) -> str:
    if not isinstance(raw_value, str):
        return "unknown"
    normalized = raw_value.strip().lower()
    if normalized in {"bidirectional", "payer_to_payee", "payee_to_payer"}:
        return normalized
    return "unknown"


def normalize_optional_text(raw_value: Any) -> str:
    if not isinstance(raw_value, str):
        return ""
    return raw_value.strip()


def normalize_string_list(raw_value: Any) -> list[str]:
    if not isinstance(raw_value, list):
        return []
    values: list[str] = []
    for item in raw_value:
        if isinstance(item, str):
            normalized = item.strip()
            if normalized:
                values.append(normalized)
    return values


def normalize_confidence(raw_value: Any) -> float:
    try:
        confidence = float(raw_value)
    except (TypeError, ValueError):
        return 0.8
    return max(0.0, min(1.0, confidence))


def infer_rate_from_text(paragraph_text: str) -> str | None:
    match = PERCENT_RATE_PATTERN.search(paragraph_text)
    if not match:
        return None
    return f"{match.group(1)}%"


def normalize_rate(raw_value: Any, inferred_rate: str | None) -> str:
    if isinstance(raw_value, str):
        normalized = raw_value.strip()
        if normalized and normalized.upper() != "N/A":
            return normalized
    return inferred_rate or "N/A"


def normalize_conditions(
    conditions: list[str],
    *,
    rule_type: str,
    paragraph_text: str,
) -> list[str]:
    if conditions:
        return conditions

    lowered_text = paragraph_text.lower()
    if is_rate_limit_rule_type(rule_type):
        defaults = [
            "The treaty rate cap applies only if the payment qualifies for treaty treatment."
        ]
        if "gross amount" in lowered_text:
            defaults.append("The stated cap applies to the gross amount of the payment.")
        return defaults

    if rule_type == "taxation_right":
        return [
            "This paragraph allocates taxing rights between the treaty jurisdictions.",
            "This paragraph does not by itself state a reduced withholding cap.",
        ]

    return []


def normalize_review_reason(
    review_reason: str,
    *,
    rule_type: str,
    paragraph_text: str,
    rate: str,
) -> str:
    if review_reason:
        return review_reason

    if rule_type == "taxation_right":
        return (
            "Taxing-right paragraph extracted for context; a separate rate-bearing paragraph may still control the treaty cap."
        )

    if is_rate_limit_rule_type(rule_type):
        if rate != "N/A":
            return (
                f"Rate cap extracted from the paragraph text at {rate}; treaty eligibility still requires fact review."
            )
        if "gross amount" in paragraph_text.lower():
            return (
                "Rate-limitation paragraph extracted from gross-amount wording; treaty eligibility still requires fact review."
            )

    return "LLM-extracted treaty rule requires manual review before reliance."


def is_rate_limit_rule_type(rule_type: str) -> bool:
    normalized = rule_type.strip().lower()
    return normalized in {"rate_limitation", "source_tax_limit", "withholding_tax_cap"}
