from __future__ import annotations

import json
import re
from typing import Any
from urllib import error, request

from app.llm_input_parser import (
    LLMInputParserConfig,
    extract_json_content,
    load_config_from_env,
)


class LLMDocumentExtractionError(RuntimeError):
    pass


SOURCE_EXTRACTION_MIN_TIMEOUT_SECONDS = 180
PERCENT_RATE_PATTERN = re.compile(r"(\d+)\s+per\s+cent", re.IGNORECASE)
ENUMERATED_RATE_BRANCH_PATTERN = re.compile(
    r"\(([a-z])\)\s*(\d+)\s+per\s+cent\s+of\s+the\s+gross\s+amount\s+of\s+the\s+dividends\s*(.*?)(?=(\([a-z]\)\s*\d+\s+per\s+cent)|$)",
    re.IGNORECASE,
)


def build_request_payload(raw_text: str, model: str, source_language: str) -> dict[str, Any]:
    system_prompt = (
        "You extract structured treaty article data for an offline tax-treaty ingestion pipeline. "
        "Return only JSON with a top-level key parsed_articles. "
        "Each article must include: article_number, article_title, income_type, summary, article_notes, paragraphs. "
        "Each paragraph must include: paragraph_number, source_reference, text, rules. "
        "Each rule must include: rule_type, rate, direction, conditions, review_reason, extraction_confidence. "
        'Required JSON field names include "income_type", "paragraph_number", and "extraction_confidence". '
        "Use income_type only from: dividends, interest, royalties, unknown. "
        "Use direction only from: bidirectional, payer_to_payee, payee_to_payer, unknown. "
        "Keep extraction_confidence between 0 and 1. "
        f"The source language is {source_language}. "
        "If the text does not contain a usable treaty article, return parsed_articles as an empty list."
    )

    return {
        "model": model,
        "temperature": 0,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": raw_text},
        ],
    }


def extract_source_payload_from_text(
    raw_text: str,
    *,
    document_id: str,
    title: str,
    document_type: str,
    jurisdictions: list[str],
    source_language: str = "en",
    config: LLMInputParserConfig | None = None,
) -> dict | None:
    resolved_config = config or load_config_from_env()
    if resolved_config is None:
        return None
    pair_id = build_pair_id(jurisdictions)

    payload = build_request_payload(raw_text, resolved_config.model, source_language)
    body = json.dumps(payload).encode("utf-8")
    http_request = request.Request(
        url=f"{resolved_config.base_url}/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {resolved_config.api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with request.urlopen(
            http_request,
            timeout=max(resolved_config.timeout_seconds, SOURCE_EXTRACTION_MIN_TIMEOUT_SECONDS),
        ) as response:
            response_payload = json.loads(response.read().decode("utf-8"))
    except (error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        raise LLMDocumentExtractionError(str(exc)) from exc

    try:
        content = response_payload["choices"][0]["message"]["content"]
        model_payload = json.loads(extract_json_content(content))
    except (KeyError, IndexError, TypeError, json.JSONDecodeError) as exc:
        raise LLMDocumentExtractionError(
            "Failed to parse structured JSON from LLM document response."
        ) from exc

    return {
        "document": {
            "document_id": document_id,
            "title": title,
            "document_type": document_type,
            "jurisdictions": jurisdictions,
            "notes": [
                "Generated by constrained LLM document extraction."
            ],
        },
        "parsed_articles": [
            normalize_article(
                article,
                source_language=source_language,
                pair_id=pair_id,
            )
            for article in model_payload.get("parsed_articles", [])
        ],
    }


def build_pair_id(jurisdictions: list[str]) -> str:
    return "-".join(jurisdiction.strip().lower() for jurisdiction in sorted(jurisdictions))


def normalize_article(
    article: dict[str, Any],
    *,
    source_language: str,
    pair_id: str,
) -> dict[str, Any]:
    article_number = str(article["article_number"]).strip()
    article_title = str(article["article_title"]).strip()
    paragraphs = article.get("paragraphs", [])

    return {
        "article_number": article_number,
        "article_title": article_title,
        "article_label": f"Article {article_number}",
        "income_type": normalize_income_type(article.get("income_type")),
        "summary": normalize_optional_text(article.get("summary")),
        "article_notes": normalize_string_list(article.get("article_notes")),
        "paragraphs": [
            normalize_paragraph(
                paragraph,
                article_number=article_number,
                pair_id=pair_id,
                source_language=source_language,
            )
            for paragraph in paragraphs
        ],
    }


def normalize_paragraph(
    paragraph: dict[str, Any],
    *,
    article_number: str,
    pair_id: str,
    source_language: str,
) -> dict[str, Any]:
    paragraph_number = str(paragraph["paragraph_number"]).strip()
    paragraph_id = f"art{article_number}-p{paragraph_number}"
    segment_id = f"{paragraph_id}-s1"
    source_reference = normalize_optional_text(paragraph.get("source_reference"))
    if not source_reference:
        source_reference = f"Article {article_number}({paragraph_number})"
    paragraph_text = normalize_optional_text(paragraph.get("text"))

    rules = paragraph.get("rules", [])
    inferred_rate = infer_rate_from_text(paragraph_text)
    inferred_branches = infer_enumerated_rate_branches(paragraph_text)
    branch_hints = assign_branch_hints_to_rules(rules, inferred_branches)
    normalized_rules: list[dict[str, Any]] = []
    for index, rule in enumerate(rules, start=1):
        rule_type = normalize_optional_text(rule.get("rule_type")) or "treaty_scope_note"
        branch_hint = branch_hints[index - 1]
        normalized_rate = normalize_rate(
            rule.get("rate"),
            rule_type=rule_type,
            inferred_rate=inferred_rate,
            inferred_branch_rate=branch_hint["rate"] if branch_hint else None,
        )
        normalized_rules.append(
            {
                "rule_id": f"{pair_id}-art{article_number}-p{paragraph_number}-r{index}",
                "rule_type": rule_type,
                "rate": normalized_rate,
                "direction": normalize_direction(rule.get("direction")),
                "candidate_rank": index,
                "is_primary_candidate": False,
                "extraction_confidence": normalize_confidence(rule.get("extraction_confidence")),
                "derived_from_segments": [segment_id],
                "conditions": normalize_conditions(
                    normalize_string_list(rule.get("conditions")),
                    rule_type=rule_type,
                    paragraph_text=paragraph_text,
                    branch_hint=branch_hint,
                ),
                "human_review_required": True,
                "review_reason": normalize_review_reason(
                    normalize_optional_text(rule.get("review_reason")),
                    rule_type=rule_type,
                    paragraph_text=paragraph_text,
                    rate=normalized_rate,
                    branch_hint=branch_hint,
                ),
            }
        )

    primary_rule_index = choose_primary_rule_index(normalized_rules)
    normalized_rules[primary_rule_index]["is_primary_candidate"] = True

    return {
        "paragraph_id": paragraph_id,
        "paragraph_label": f"Article {article_number}({paragraph_number})",
        "source_reference": source_reference,
        "source_language": normalize_optional_text(paragraph.get("source_language")) or source_language,
        "source_segments": [
            {
                "segment_id": segment_id,
                "segment_order": 1,
                "page_hint": None,
                "source_kind": "article_paragraph",
                "text_quality": "clean",
                "normalization_status": "verbatim",
                "text": paragraph_text,
            }
        ],
        "extracted_rules": normalized_rules,
    }


def normalize_income_type(raw_value: Any) -> str:
    if not isinstance(raw_value, str):
        return "unknown"
    normalized = raw_value.strip().lower()
    if normalized in {"dividends", "interest", "royalties"}:
        return normalized
    return "unknown"


def normalize_direction(raw_value: Any) -> str:
    if not isinstance(raw_value, str):
        return "unknown"
    normalized = raw_value.strip().lower()
    if normalized in {"bidirectional", "payer_to_payee", "payee_to_payer"}:
        return normalized
    return "unknown"


def normalize_optional_text(raw_value: Any) -> str:
    if not isinstance(raw_value, str):
        return ""
    return raw_value.strip()


def normalize_string_list(raw_value: Any) -> list[str]:
    if not isinstance(raw_value, list):
        return []
    values: list[str] = []
    for item in raw_value:
        if isinstance(item, str):
            normalized = item.strip()
            if normalized:
                values.append(normalized)
    return values


def normalize_confidence(raw_value: Any) -> float:
    try:
        confidence = float(raw_value)
    except (TypeError, ValueError):
        return 0.8
    return max(0.0, min(1.0, confidence))


def infer_rate_from_text(paragraph_text: str) -> str | None:
    match = PERCENT_RATE_PATTERN.search(paragraph_text)
    if not match:
        return None
    return f"{match.group(1)}%"


def normalize_rate(
    raw_value: Any,
    *,
    rule_type: str,
    inferred_rate: str | None,
    inferred_branch_rate: str | None = None,
) -> str:
    if isinstance(raw_value, str):
        normalized = raw_value.strip()
        if (
            normalized
            and normalized.upper() != "N/A"
            and (inferred_branch_rate is None or normalized == inferred_branch_rate)
        ):
            return normalized
    if not is_rate_limit_rule_type(rule_type):
        return "N/A"
    return inferred_branch_rate or inferred_rate or "N/A"


def normalize_conditions(
    conditions: list[str],
    *,
    rule_type: str,
    paragraph_text: str,
    branch_hint: dict[str, str] | None = None,
) -> list[str]:
    if conditions:
        return conditions

    if branch_hint and branch_hint.get("condition"):
        return [branch_hint["condition"]]

    lowered_text = paragraph_text.lower()
    if is_rate_limit_rule_type(rule_type):
        defaults = [
            "The treaty rate cap applies only if the payment qualifies for treaty treatment."
        ]
        if "gross amount" in lowered_text:
            defaults.append("The stated cap applies to the gross amount of the payment.")
        return defaults

    if rule_type == "taxation_right":
        return [
            "This paragraph allocates taxing rights between the treaty jurisdictions.",
            "This paragraph does not by itself state a reduced withholding cap.",
        ]

    return []


def normalize_review_reason(
    review_reason: str,
    *,
    rule_type: str,
    paragraph_text: str,
    rate: str,
    branch_hint: dict[str, str] | None = None,
) -> str:
    if review_reason:
        return review_reason

    if rule_type == "taxation_right":
        return (
            "Taxing-right paragraph extracted for context; a separate rate-bearing paragraph may still control the treaty cap."
        )

    if is_rate_limit_rule_type(rule_type):
        if branch_hint and branch_hint.get("condition"):
            return (
                f"Rate cap extracted from the paragraph text at {rate}; "
                f"the branch condition is: {branch_hint['condition']}"
            )
        if rate != "N/A":
            return (
                f"Rate cap extracted from the paragraph text at {rate}; treaty eligibility still requires fact review."
            )
        if "gross amount" in paragraph_text.lower():
            return (
                "Rate-limitation paragraph extracted from gross-amount wording; treaty eligibility still requires fact review."
            )

    return "LLM-extracted treaty rule requires manual review before reliance."


def is_rate_limit_rule_type(rule_type: str) -> bool:
    normalized = rule_type.strip().lower()
    return normalized in {
        "rate_limitation",
        "source_tax_limit",
        "withholding_tax_cap",
        "withholding_tax_limit",
    }


def infer_enumerated_rate_branches(paragraph_text: str) -> list[dict[str, str]]:
    branches: list[dict[str, str]] = []
    for match in ENUMERATED_RATE_BRANCH_PATTERN.finditer(paragraph_text):
        rate = f"{match.group(2)}%"
        tail = re.sub(r"\s+", " ", match.group(3)).strip(" ;:.")
        condition = normalize_branch_condition_text(tail)
        branches.append({"rate": rate, "condition": condition})
    return branches


def normalize_branch_condition_text(condition_tail: str) -> str:
    if not condition_tail:
        return ""
    normalized = condition_tail.strip()
    if not normalized:
        return ""
    normalized = normalized[0].upper() + normalized[1:]
    if not normalized.endswith("."):
        normalized += "."
    return normalized


def assign_branch_hints_to_rules(
    rules: list[dict[str, Any]],
    inferred_branches: list[dict[str, str]],
) -> list[dict[str, str] | None]:
    if not inferred_branches:
        return [None] * len(rules)

    assignments: list[dict[str, str] | None] = [None] * len(rules)
    used_branch_indexes: set[int] = set()

    for rule_index, rule in enumerate(rules):
        if not is_rate_limit_rule_type(normalize_optional_text(rule.get("rule_type")) or ""):
            continue

        best_branch_index = None
        best_score = 0
        for branch_index, branch in enumerate(inferred_branches):
            if branch_index in used_branch_indexes:
                continue
            score = branch_match_score(rule, branch)
            if score > best_score:
                best_score = score
                best_branch_index = branch_index

        if best_branch_index is not None and best_score > 0:
            assignments[rule_index] = inferred_branches[best_branch_index]
            used_branch_indexes.add(best_branch_index)

    for rule_index, rule in enumerate(rules):
        if assignments[rule_index] is not None:
            continue
        if not is_rate_limit_rule_type(normalize_optional_text(rule.get("rule_type")) or ""):
            continue
        for branch_index, branch in enumerate(inferred_branches):
            if branch_index in used_branch_indexes:
                continue
            assignments[rule_index] = branch
            used_branch_indexes.add(branch_index)
            break

    return assignments


def choose_primary_rule_index(rules: list[dict[str, Any]]) -> int:
    for index, rule in enumerate(rules):
        if is_rate_limit_rule_type(normalize_optional_text(rule.get("rule_type")) or ""):
            return index
    return 0


def branch_match_score(rule: dict[str, Any], branch: dict[str, str]) -> int:
    score = 0
    raw_rate = normalize_optional_text(rule.get("rate"))
    if raw_rate and raw_rate.upper() != "N/A" and raw_rate == branch["rate"]:
        score += 100

    existing_text = " ".join(
        normalize_string_list(rule.get("conditions"))
        + [normalize_optional_text(rule.get("review_reason"))]
    ).lower()
    if existing_text and branch.get("condition"):
        branch_condition = branch["condition"].lower().rstrip(".")
        if branch_condition and branch_condition in existing_text:
            score += 50
        else:
            score += lexical_overlap_score(existing_text, branch_condition)

    return score


def lexical_overlap_score(left: str, right: str) -> int:
    left_tokens = meaningful_tokens(left)
    right_tokens = meaningful_tokens(right)
    if not left_tokens or not right_tokens:
        return 0
    return len(left_tokens & right_tokens)


def meaningful_tokens(text: str) -> set[str]:
    stopwords = {
        "the",
        "and",
        "of",
        "a",
        "an",
        "is",
        "are",
        "to",
        "if",
        "in",
        "all",
        "other",
        "cases",
        "case",
        "rate",
        "branch",
    }
    return {
        token
        for token in re.findall(r"[a-z0-9]+", text.lower())
        if len(token) > 2 and token not in stopwords
    }
